// <auto-generated />
namespace ImageGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ImageContentId_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageContentId_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201401240553290_ImageContentId_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
